name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 3 * * *"   # всеки ден 03:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: valchev0
          BRANCH_NAME: profile-summary-card-output
          THEME: github_dark
